name: Deploy

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: tlienart/xranklin-build-action@v3.2
        with:
          # ADJUST THE FOLLOWING
          BRANCH: "devwip"
          # if it's a personal site, use "" otherwise use the name of the repo
          BASE_URL_PREFIX: "layout-tester"

          # ===================================================================
          # DON'T CHANGE THE FOLLOWING UNLESS YOU HAVE GOOD REASONS TO
          # >> amounts to build(clear=true) when commit message contains [clear]
          CLEAR_CACHE: ${{ contains(github.event.head_commit.message, '[clear]') }}
          # >> change the digit at the end if, for some reason, you believe
          # that the cache used by the github action has an issue
          CACHE_KEY: "franklin-cache"
      - name: Wait 30s for deployment
        run: sleep 30
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker@v1.0.1
        with:
          # Required:
          url: 'https://tlienart.github.io/layout-tester/'
          # optional:
          honorRobotExclusions: false
          ignorePatterns: 'github,google'
          recursiveLinks: false # Check all URLs on all reachable pages (could take a while)
      - name: Broken links report
        run: echo "${{steps.link-report.outputs.result}}"