name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      # https://github.com/tlienart/xranklin-build-action/tags
      - uses: tlienart/xranklin-build-action@v3.2
        with:
          BRANCH: "devwip"
          BASE_URL_PREFIX: "layout-tester"
          PYTHON_LIBS: "matplotlib pandas"
          # XXX make this post later
          JULIA_PRE: "include(\"stork.jl\")"

          # ===================================================================
          # DON'T CHANGE THE FOLLOWING UNLESS YOU HAVE GOOD REASONS TO
          # >> amounts to build(clear=true) when commit message contains [clear]
          CLEAR_CACHE: ${{ contains(github.event.head_commit.message, '[clear]') }}
          # >> change the digit at the end if, for some reason, you believe
          # that the cache used by the github action has an issue
          CACHE_KEY: "franklin-cache"
